### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by Pujan-Karki** [dineshdb/ictc_events#1]
8080 port not working.

**Comment by dineshdb** [comment]
I will look into it soon. However, I will need more detailed info on this.

**Comment by Pujan-Karki** [comment]
Created Database, built backend, java file runs successfully, but nothing comes up in port 8080. And after running frontend and backend, nothing happens after logging in.

**Comment by dineshdb** [comment]
Have you tried updating each repo individually using git instead of using submodule? Most of the time, the submodules might not be updated (especially during development). Remember to pull each repo individually as you develop each repo parallelly.

**Comment by dineshdb** [comment]
I have made some changes and updated the Readme accordingly. The main change is you use ``npm run live`` now instead of ``npm run start`` for development. Good luck.

**Comment by dineshdb** [comment]
Just for clarification, the api designed to be used with an proxy but you were not running one. live setting now does that exactly.
